name: CD

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
    branches:
      - main

permissions:
  actions: read
  contents: read

concurrency:
  group: cd-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy_dev:
    name: Deploy To Dev
    if: >
      github.event_name == 'workflow_run' &&
      github.event.workflow_run.conclusion == 'success'
    uses: ./.github/workflows/deploy-dev.yml
    secrets: inherit
    with:
      artifact_name: acme-los-deployable-${{ github.event.workflow_run.head_sha }}
      artifact_run_id: ${{ github.event.workflow_run.id }}
      source_ref: ${{ github.event.workflow_run.head_sha }}

  deploy_qa:
    name: Deploy To QA
    needs:
      - deploy_dev
    uses: ./.github/workflows/deploy-qa.yml
    secrets: inherit
    with:
      artifact_name: acme-los-deployable-${{ github.event.workflow_run.head_sha }}
      artifact_run_id: ${{ github.event.workflow_run.id }}
      source_ref: ${{ github.event.workflow_run.head_sha }}

  deploy_stg:
    name: Deploy To Staging
    needs:
      - deploy_qa
    uses: ./.github/workflows/deploy-stg.yml
    secrets: inherit
    with:
      artifact_name: acme-los-deployable-${{ github.event.workflow_run.head_sha }}
      artifact_run_id: ${{ github.event.workflow_run.id }}
      source_ref: ${{ github.event.workflow_run.head_sha }}

  deploy_prod:
    name: Deploy To Production
    needs:
      - deploy_stg
    uses: ./.github/workflows/deploy-prod.yml
    secrets: inherit
    with:
      artifact_name: acme-los-deployable-${{ github.event.workflow_run.head_sha }}
      artifact_run_id: ${{ github.event.workflow_run.id }}
      source_ref: ${{ github.event.workflow_run.head_sha }}
