name: CD

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
    branches:
      - main

permissions:
  id-token: write
  actions: read
  contents: read

concurrency:
  group: cd-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy_dev:
    name: Deploy To Dev
    if: >
      github.event_name == 'workflow_run' &&
      github.event.workflow_run.conclusion == 'success'
    uses: ./.github/workflows/deploy-dev.yml
    permissions:
      id-token: write
      actions: read
      contents: read
    secrets: inherit
    with:
      artifact_name: acme-los-deployable-${{ github.event.workflow_run.head_sha }}
      artifact_run_id: ${{ github.event.workflow_run.id }}
      source_ref: ${{ github.event.workflow_run.head_sha }}
